### PR TITLE
Refactored Deepbots: DeepbotsEnv & Robot Class

### LINKED ISSUE #84: Usage of snake_case
Make sure all deepworlds variables follow the snake_case convention.

### PR DESCRIPTION
**Pull request by KelvinYang0320**
This PR  is corresponding to 
*  https://github.com/aidudezzz/deepbots/pull/116

### CODE REVIEW

**Review by tsampazk — COMMENTED** [review]
Changes look good @KelvinYang0320 thanks! Let's wait for the changes in deepbots to finalize and we get at least a new dev release, before we get this merged though.

**Comment by KelvinYang0320** [comment]
@tsampazk This PR works fine with the latest KHR-3HV example since it doesn't use an emitter/receiver. 
We can rebase and merge it when you think it is ready. :smile:

**Comment by KelvinYang0320** [comment]
@tsampazk I think I didn't rename all function names and variable names to snake_case last time.
I add a few commits to this PR. Could you check if all examples in deepworlds work fine again? Thank you!

**Comment by tsampazk** [comment]
We can change stuff regarding test pypi like this one https://github.com/KelvinYang0320/deepworlds/blob/45b4a6b1ad3a2ece68b4dbfb0ab65be6caa7caed/README.md?plain=1#L25 .

I don't think there are other similar stuff that need changing in the deepworlds repo, right?

**Comment by tsampazk** [comment]
Hey @KelvinYang0320 , should we go ahead and merge this for the examples to work properly  for the 1.0 release? Is there anything left to do?

**Comment by KelvinYang0320** [comment]
@tsampazk  Could you check if all examples work fine again for me? I just rebased and squashed the commits. 
If all examples work without error, I think we are ready to go.

**Comment by tsampazk** [comment]
Sure thing @KelvinYang0320 , thank you

**Review by tsampazk — APPROVED** [review]
Looks good, thank you very much @KelvinYang0320  :)

**Pull request merged**
