### PR TITLE
Updated Installation Instructions: deepbots 0.1.3.dev -> 1.0.0

### PR DESCRIPTION
**Pull request by KelvinYang0320**
- [x] Removed TestPyPI url on main README
* https://github.com/aidudezzz/deepworlds/pull/80#issuecomment-1455138323
- [x] Updated Panda README
- [x] Removed cartpolt_discrete SB3 README since it is deprecated.

### CODE REVIEW

**Comment by KelvinYang0320** [comment]
> We can change stuff regarding test pypi like this one https://github.com/KelvinYang0320/deepworlds/blob/45b4a6b1ad3a2ece68b4dbfb0ab65be6caa7caed/README.md?plain=1#L25 .
> I don't think there are other similar stuff that need changing in the deepworlds repo, right?

@eakirtas @tsampazk Do you want to remove the [README](https://github.com/aidudezzz/deepworlds/tree/dev/examples/cartpole/cartpole_discrete/controllers/robot_supervisor_manager_Stable_Baselines) in the cartpole_discrete SB3 version?

**Comment by tsampazk** [comment]
> > We can change stuff regarding test pypi like this one https://github.com/KelvinYang0320/deepworlds/blob/45b4a6b1ad3a2ece68b4dbfb0ab65be6caa7caed/README.md?plain=1#L25 .
> > I don't think there are other similar stuff that need changing in the deepworlds repo, right?
> 
> @eakirtas @tsampazk Do you want to remove the [README](https://github.com/aidudezzz/deepworlds/tree/dev/examples/cartpole/cartpole_discrete/controllers/robot_supervisor_manager_Stable_Baselines) in the cartpole_discrete SB3 version?

I guess its deprecated now since we have the requirements files, so we can go ahead and remove it altogether, or maybe provide a really short one or two-sentence description on what the example actually is, which algorithm from sb3 it is using etc.

**Comment by KelvinYang0320** [comment]
> so we can go ahead and remove it altogether

@tsampazk I agree with you. I will update the PR. Thanks!

**Review by tsampazk — APPROVED** [review]
Looks good, thank you!

**Comment by KelvinYang0320** [comment]
@tsampazk Thank you! 😄

**Pull request merged**
