### PR TITLE
Added requirements

### PR DESCRIPTION
**Pull request by KelvinYang0320**
Users can `pip install -r <path to requirements file>` or `conda install --yes --file <path to requirements file>` to install specific  packages for each example.
* https://github.com/aidudezzz/deepbots/issues/102

### CODE REVIEW

**Comment by tsampazk** [comment]
Hey @KelvinYang0320, these requirements files look really useful. I was wondering if it would be better to use snake_case in the file names? What do you think? 

I am already adding instructions on the main readme regarding how to run an example using these requirement files as a first step.

**Comment by KelvinYang0320** [comment]
>  I was wondering if it would be better to use snake_case in the file names? What do you think?

@tsampazk I am okay with lowerCamelCase/snake_case for requirement files since we set each requirement file name as its wbt file name.
* lowerCamelCase: webots coding format
* snake_case: latest PEP8

I will change all names to snake_case if you think it will be better. 😄 
What is the snake_case name for each example?
```
cartPoleWorldEmitterReceiver.wbt -> cartpole_world_emitter_receiver.wbt
cartPoleWorldRobotSupervisor.wbt -> cartpole_world_robot_supervisor.wbt
cartPoleWorldRobotSupervisorStableBaselines.wbt -> cartpole_world_robot_supervisor_stable_baselines.wbt

cartPoleWorldEmitterReceiver.wbt -> cartpole_world_emitter_receiver.wbt
cartPoleWorldRobotSupervisor.wbt -> cartpole_world_robot_supervisor.wbt

small_world.wbt -> (already in snake_case)

khr-3hv.wbt -> khr_3hv.wbt

pandaRL_training.wbt -> panda_goal_reaching.wbt

pit_escape.wbt -> (already in snake_case)
```

**Comment by tsampazk** [comment]
Your name suggestions look good, we can go ahead and rename both the worlds and requirement files to snake_case! Thank you!

**Comment by KelvinYang0320** [comment]
@tsampazk Thank you for the suggestion. I have renamed all files to snake_case.
I would like to keep two commits for this PR without squashing them since these are two tasks.
Note that I didn't specify most of the package versions since I am not sure which version is better and if that is necessary.

**Comment by tsampazk** [comment]
As far as i can tell, only gym is required to be specified as it has breaking changes in newer versions. For all other requirements we can keep them unspecified as long as there are no issues.

**Review by tsampazk — APPROVED** [review]
Looks good @KelvinYang0320, thank you!

**Pull request merged**
