### PR TITLE
[panda] solved by IKPY without RL

### LINKED ISSUE #39: About panda robot demo
I try to use the panda world file from the demo, and use the ikpy to get link, but I got wrong link amount? Does anyone know the reason?

### PR DESCRIPTION
**Pull request by KelvinYang0320**

### CODE REVIEW

**Review by eakirtas — APPROVED** [review]
Code look good to me. However, I feel that is better to use same `ArmUtils.py` for both solutions (RY, IKPY). Could you address this on a following PR?

**Comment by KelvinYang0320** [comment]
@ManosMagnus Should we maintain only one `ArmUtil.py` like the following directories structure? 
```
\panda_goal_reaching
    \controllers
        \ArmUtil.py (created)
        \robot_supervisor_manager
            \ArmUtil.py (deleted)
            \...
        \IKPY
            \ArmUtil.py (deleted)
            \...   
```
Or make `robot_supervisor_manager/ArmUtil.py` be exactly the same as `IKPY/ArmUtil.py`?
Since they are different controllers, I am not sure which one is better.

**Comment by eakirtas** [comment]
> @ManosMagnus Should we maintain only one `ArmUtil.py` like the following directories structure?
> 
> ```
> \panda_goal_reaching
>     \controllers
>         \ArmUtil.py (created)
>         \robot_supervisor_manager
>             \ArmUtil.py (deleted)
>             \...
>         \IKPY
>             \ArmUtil.py (deleted)
>             \...   
> ```
> 
> Or make `robot_supervisor_manager/ArmUtil.py` be exactly the same as `IKPY/ArmUtil.py`?
> Since they are different controllers, I am not sure which one is better.

First approach looks good to me

**Comment by KelvinYang0320** [comment]
@ManosMagnus Thank you. I will address it on the following PR.

**Pull request merged**
